/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetupRouteImport } from './routes/_auth.setup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthChangePasswordRouteImport } from './routes/_auth.change-password'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppProgramsRouteImport } from './routes/_app.programs'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppMediaRouteImport } from './routes/_app.media'
import { Route as AppHostsRouteImport } from './routes/_app.hosts'
import { Route as AppBroadcastRouteImport } from './routes/_app.broadcast'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsRoute = AppProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppHostsRoute = AppHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastRoute = AppBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/broadcast': typeof AppBroadcastRoute
  '/hosts': typeof AppHostsRoute
  '/media': typeof AppMediaRoute
  '/members': typeof AppMembersRoute
  '/programs': typeof AppProgramsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/broadcast': typeof AppBroadcastRoute
  '/hosts': typeof AppHostsRoute
  '/media': typeof AppMediaRoute
  '/members': typeof AppMembersRoute
  '/programs': typeof AppProgramsRoute
  '/schedule': typeof AppScheduleRoute
  '/settings': typeof AppSettingsRoute
  '/change-password': typeof AuthChangePasswordRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/broadcast': typeof AppBroadcastRoute
  '/_app/hosts': typeof AppHostsRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/programs': typeof AppProgramsRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/change-password': typeof AuthChangePasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/setup': typeof AuthSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/broadcast'
    | '/hosts'
    | '/media'
    | '/members'
    | '/programs'
    | '/schedule'
    | '/settings'
    | '/change-password'
    | '/login'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/broadcast'
    | '/hosts'
    | '/media'
    | '/members'
    | '/programs'
    | '/schedule'
    | '/settings'
    | '/change-password'
    | '/login'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/broadcast'
    | '/_app/hosts'
    | '/_app/media'
    | '/_app/members'
    | '/_app/programs'
    | '/_app/schedule'
    | '/_app/settings'
    | '/_auth/change-password'
    | '/_auth/login'
    | '/_auth/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/change-password': {
      id: '/_auth/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs': {
      id: '/_app/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AppProgramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts': {
      id: '/_app/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof AppHostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast': {
      id: '/_app/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AppBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBroadcastRoute: typeof AppBroadcastRoute
  AppHostsRoute: typeof AppHostsRoute
  AppMediaRoute: typeof AppMediaRoute
  AppMembersRoute: typeof AppMembersRoute
  AppProgramsRoute: typeof AppProgramsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBroadcastRoute: AppBroadcastRoute,
  AppHostsRoute: AppHostsRoute,
  AppMediaRoute: AppMediaRoute,
  AppMembersRoute: AppMembersRoute,
  AppProgramsRoute: AppProgramsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
