
[Interface]
PrivateKey = 4pgizltR/4aSLPlzAu1+zZfyLHnyeDErNLE1DNsFFE0=
Address = fdaa:77:f50e:a7b:dc6:ccaf:3a89:4002/120
DNS = fdaa:77:f50e::3

[Peer]
PublicKey = eCP0xi9xD62HqHSEEa3skpxpFUTxhjvubgDlLfVZyFk=
AllowedIPs = fdaa:77:f50e::/48
Endpoint = lhr1.gateway.6pn.dev:51820
PersistentKeepalive = 15

